language: node_js
before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@1
  - npm install -g codecov
install:
  - npm ci || npm install
before_script: greenkeeper-lockfile-update
script:
  - npm test
  - codecov
after_script: greenkeeper-lockfile-upload
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npm run build
node_js:
  - "8"
cache:
  directories:
    - $HOME/.npm
deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: build
