language: node_js
after_success:
  - npm run build
node_js:
  - "8"
cache:
  directories:
    - $HOME/.npm
deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: build
