language: node_js
before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run build
node_js:
  - "8"
cache:
  directories:
    - $HOME/.npm
deploy:
  skip_cleanup: true
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: build
