export const INCREMENT_ITEM_COUNT = 'INCREMENT_ITEM_COUNT';
export const SET_LOADED = 'SET_LOADED';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';
export const SET_PROGRESS = 'SET_PROGRESS';
export const SET_GIFT_COUNT = 'SET_GIFT_COUNT';
