export const INCREMENT_ITEM_COUNT = 'INCREMENT_ITEM_COUNT';
export const RESET_ITEM_COUNT = 'RESET_ITEM_COUNT';
export const RESET_ITEM_COUNTS = 'RESET_ITEM_COUNTS';
export const SET_LOADED = 'SET_LOADED';
